export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_LOADING = "GET_POSTS_LOADING";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";
export const CREATE_POSTS_SUCCESS = "CREATE_POSTS_SUCCESS";
export const CREATE_POSTS_LOADING = "CREATE_POSTS_LOADING";
export const CREATE_POSTS_ERROR = "CREATE_POSTS_ERROR";
